---
output: 
  html_document: 
    keep_md: yes
---
##1.加载需要的包
```{r}
library(XML)
library(dplyr)
```
##2.得到url
```{r}
url<-NULL
for(i in 1:29){
  url[i]<-paste0("http://www.youku.com/v_olist/c_97_g__a_%E5%A4%A7%E9%99%86_sg__mt__lg__q__s_1_r_0_u_0_pt_0_av_0_ag_0_sg__pr__h__d_4_p_",i,".html")
}
```

##3.获取单页data
```{r}
getyouku<-function(URL){
  Sys.sleep(runif(1,1,2))
  doc<-htmlParse(URL[1],encoding="UTF-8")
  rootNode<-xmlRoot(doc)
##获取电视剧名称 
  title<-xpathSApply(rootNode,"//div[@class='p-meta-title']",xmlValue)
#获取观看人数和评分
  num<-xpathSApply(rootNode,"//span[@class='p-num']",xmlValue)
  score<-xpathSApply(rootNode,"//span[@class='p-rating']",xmlValue)
##电视剧集数
  status<-xpathSApply(rootNode,"//span[@class='p-status']",xmlValue)
##合并成数据框
  data<-data.frame(title=title,num=num,score=score,status=status)
  data
}
```

##4.合并
```{r}
data<-NULL
for(i in 1:29){
  data<-rbind(data,getyouku(url[i]))
}
```

##5.简单分析
```{r}
data$num<-as.character(data$num)
data$score<-as.numeric(as.character(data$score))
head(data)
status1<-as.data.frame(table(data$status))
status1<-status1 %>% arrange(-Freq) %>% rename("集数"=Var1,"频率"=Freq)
barplot(status1$频率)
```